name: sync-docs

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Inspect upstream
        run: |
          git clone --depth 1 https://github.com/canonical/postgresql-operator /tmp/pgop
          echo "===== ROOT ====="
          ls -la /tmp/pgop
          echo "===== BRANCH ====="
          cd /tmp/pgop && git branch -a
